# Generated by Django 5.2.6 on 2025-09-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshots',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('snapshot_time', models.DateTimeField()),
                ('metrics', models.JSONField()),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-date'], name='idx_daily_date')],
            },
        ),
        migrations.CreateModel(
            name='MarketMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('metric_name', models.CharField(max_length=50)),
                ('metric_value', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('data_type', models.CharField(default='premarket', max_length=20)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_name', '-timestamp'], name='metrics_mar_metric__93f915_idx')],
                'unique_together': {('timestamp', 'metric_name')},
            },
        ),
    ]
